# Schemas module
from app.schemas.analysis import (
    AgentResultResponse,
    AgentTypeEnum,
    AnalysisErrorResponse,
    FullAnalysisResponse,
    SingleAnalysisResponse,
)
from app.schemas.stock import (
    StockQuoteResponse,
    StockHistoryResponse,
    StockInfoResponse,
    StockFinancialsResponse,
    SearchResponse,
)
from app.schemas.user import (
    UserCreate,
    UserLogin,
    UserResponse,
    TokenResponse,
    MessageResponse,
)
from app.schemas.watchlist import (
    WatchlistCreate,
    WatchlistUpdate,
    WatchlistResponse,
    WatchlistDetailResponse,
    WatchlistItemCreate,
    WatchlistItemResponse,
)
from app.schemas.news import (
    NewsResponse,
    NewsCreate,
    NewsFeedResponse,
    NewsAlertCreate,
    NewsAlertUpdate,
    NewsAlertResponse,
    NewsAlertListResponse,
    NewsAnalysisResponse,
    TrendingNewsResponse,
)
from app.schemas.portfolio import (
    PortfolioCreate,
    PortfolioUpdate,
    PortfolioResponse,
    PortfolioListResponse,
    PortfolioDetailResponse,
    PortfolioDetailWithQuotes,
    PortfolioSummary,
    HoldingResponse,
    HoldingWithQuote,
    HoldingsListResponse,
    TransactionCreate,
    TransactionResponse,
    TransactionListResponse,
    TransactionTypeEnum,
    CurrencyEnum,
)
from app.schemas.alert import (
    AlertConditionType,
    PriceAlertCreate,
    PriceAlertUpdate,
    PriceAlertResponse,
    PriceAlertListResponse,
    PriceAlertWithPrice,
    PushSubscriptionCreate,
    PushSubscriptionResponse,
    PushSubscriptionListResponse,
    AlertNotification,
    VAPIDKeysResponse,
)
from app.schemas.report import (
    ReportFrequency,
    ReportFormat,
    ReportStatus,
    ReportScheduleCreate,
    ReportScheduleUpdate,
    ReportScheduleResponse,
    ReportScheduleListResponse,
    ReportResponse,
    ReportListResponse,
    ReportDownloadResponse,
    ReportContent,
    StockPerformanceSummary,
    TechnicalSummary,
    NewsSummary,
    PortfolioSummaryForReport,
)

__all__ = [
    # User schemas
    "UserCreate",
    "UserLogin",
    "UserResponse",
    "TokenResponse",
    "MessageResponse",
    # Stock schemas
    "StockQuoteResponse",
    "StockHistoryResponse",
    "StockInfoResponse",
    "StockFinancialsResponse",
    "SearchResponse",
    # Watchlist schemas
    "WatchlistCreate",
    "WatchlistUpdate",
    "WatchlistResponse",
    "WatchlistDetailResponse",
    "WatchlistItemCreate",
    "WatchlistItemResponse",
    # Analysis schemas
    "AgentTypeEnum",
    "AgentResultResponse",
    "FullAnalysisResponse",
    "SingleAnalysisResponse",
    "AnalysisErrorResponse",
    # News schemas
    "NewsResponse",
    "NewsCreate",
    "NewsFeedResponse",
    "NewsAlertCreate",
    "NewsAlertUpdate",
    "NewsAlertResponse",
    "NewsAlertListResponse",
    "NewsAnalysisResponse",
    "TrendingNewsResponse",
    # Portfolio schemas
    "PortfolioCreate",
    "PortfolioUpdate",
    "PortfolioResponse",
    "PortfolioListResponse",
    "PortfolioDetailResponse",
    "PortfolioDetailWithQuotes",
    "PortfolioSummary",
    "HoldingResponse",
    "HoldingWithQuote",
    "HoldingsListResponse",
    "TransactionCreate",
    "TransactionResponse",
    "TransactionListResponse",
    "TransactionTypeEnum",
    "CurrencyEnum",
    # Alert schemas
    "AlertConditionType",
    "PriceAlertCreate",
    "PriceAlertUpdate",
    "PriceAlertResponse",
    "PriceAlertListResponse",
    "PriceAlertWithPrice",
    "PushSubscriptionCreate",
    "PushSubscriptionResponse",
    "PushSubscriptionListResponse",
    "AlertNotification",
    "VAPIDKeysResponse",
    # Report schemas
    "ReportFrequency",
    "ReportFormat",
    "ReportStatus",
    "ReportScheduleCreate",
    "ReportScheduleUpdate",
    "ReportScheduleResponse",
    "ReportScheduleListResponse",
    "ReportResponse",
    "ReportListResponse",
    "ReportDownloadResponse",
    "ReportContent",
    "StockPerformanceSummary",
    "TechnicalSummary",
    "NewsSummary",
    "PortfolioSummaryForReport",
]
